# Copyright 2015-2016 Freescale Semiconductor, Inc.
# Copyright 2017 NXP
#
# SPDX-License-Identifier:GPL-2.0+

# Layerscape PFE driver
obj-y += pfe.o		\
	 pfe_cmd.o	\
	 pfe_driver.o	\
	 pfe_eth.o	\
	 pfe_firmware.o
