# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2018 Microsoft Corporation

CYRES_ROOT=../../external/RIoT/CyReP

#obj-y += $(CYRES_ROOT)/RiotAes128.o
#obj-y += $(CYRES_ROOT)/RiotAesTables.o
obj-y += $(CYRES_ROOT)/RiotBase64.o
obj-y += $(CYRES_ROOT)/RiotCrypt.o
obj-y += $(CYRES_ROOT)/RiotDerEnc.o
obj-y += $(CYRES_ROOT)/RiotEcc.o
obj-y += $(CYRES_ROOT)/RiotHmac.o
obj-y += $(CYRES_ROOT)/RiotKdf.o
obj-y += $(CYRES_ROOT)/RiotSha256.o
obj-y += $(CYRES_ROOT)/RiotX509Bldr.o
